# coding: utf-8

"""
    LiveAgent Async Event API

    This API is for async event communication

    The version of the OpenAPI document: 1.0.12
    Contact: mcivan@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from qu.la_internal.models.handler_payload import HandlerPayload  # noqa: E501

class TestHandlerPayload(unittest.TestCase):
    """HandlerPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandlerPayload:
        """Test HandlerPayload
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandlerPayload`
        """
        model = HandlerPayload()  # noqa: E501
        if include_optional:
            return HandlerPayload(
                id = '',
                event = '',
                payload = ''
            )
        else:
            return HandlerPayload(
        )
        """

    def testHandlerPayload(self):
        """Test HandlerPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
