# coding: utf-8

"""
    LiveAgent Async Event API

    This API is for async event communication

    The version of the OpenAPI document: 1.0.12
    Contact: mcivan@qualityunit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qu.la_internal.api.events_api import EventsApi  # noqa: E501


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_execute_handler(self) -> None:
        """Test case for execute_handler

        Execute event handlers  # noqa: E501
        """
        pass

    def test_get_event_consumers(self) -> None:
        """Test case for get_event_consumers

        Get event consumer definitions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
