# coding: utf-8

"""
    LiveAgent Async Event API

    This API is for async event communication  # noqa: E501

    The version of the OpenAPI document: 1.0.8
    Contact: mcivan@qualityunit.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import qu.la_internal
from qu.la_internal.api.events_api import EventsApi  # noqa: E501
from qu.la_internal.rest import ApiException


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self):
        self.api = qu.la_internal.api.events_api.EventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_execute_handler(self):
        """Test case for execute_handler

        Execute event handlers  # noqa: E501
        """
        pass

    def test_get_event_consumers(self):
        """Test case for get_event_consumers

        Get event consumer definitions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
